# -*- coding: utf-8 -*-
"""S&P500stockMonitor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ksfMiXKsQqX0rUgeLgPFaggxPSaVPqUl

Source: Wikipedia 

David Awe
"""

import pandas as pd 
def load_data():
  url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
  html = pd.read_html(url, header = 0)
  df = html[0]
  return df

df = load_data()
df

"""Let's Examine the Sectors

"""

sector_unique = df['GICS Sector'].unique()
sector_unique

len(sector_unique)



"""Group by Sectors"""

sector = df.groupby('GICS Sector')

sector.first()

sector.describe()

"""Examine Data by Sector"""

sector.get_group('Health Care')

"""Finance Data"""

pip install yfinance

import yfinance as yf

"""List of S&P 500 Symbos"""

list(df.Symbol)

data = yf.download(
    tickers = list(df.Symbol),
    period = "ytd",
    interval = "1d",
    group_by = 'ticker',
    auto_adjust = True,
    prepost = True,
    threads = True,
    proxy = None 
)

data['AAPL']

df2 = pd.DataFrame(data['ABT'].Close)
df2['Date'] = df2.index
df2

"""Plot Closing Price of Query Symbol"""

import matplotlib.pyplot as plt
plt.fill_between(df2.Date, df2.Close, color = "skyblue", alpha = 0.3)
plt.plot(df2.Date, df2.Close, color = "skyblue", alpha = 0.8)
plt.xticks(rotation = 90)
plt.xlabel("Date")
plt.ylabel("Closing Price")

import matplotlib.pyplot as plt

def price_plot(symbol):
  df = pd.DataFrame(data[symbol].Close)
  df['Date'] = df.index
  plt.fill_between(df.Date, df.Close, color = 'skyblue', alpha = 0.3)
  plt.plot(df.Date, df.Close, color = 'skyblue', alpha = 0.8)
  plt.xticks(rotation = 90)
  plt.title(symbol, fontweight = 'bold')
  plt.xlabel('Date', fontweight = 'bold')
  plt.ylabel('Closing Price', fontweight = 'bold')
  return plt.show()

price_plot('AAPL')

for i in list(df.Symbol)[:10]:
  price_plot(i)